# version: '3.8'

services:
  # Wazuh indexer (OpenSearch)
  wazuh.indexer:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: wazuh.indexer
    hostname: wazuh.indexer
    environment:
      - cluster.name=wazuh-cluster
      - node.name=wazuh.indexer
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - wazuh-indexer-data:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"
    networks:
      - wazuh
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 60s

  # Wazuh manager
  wazuh.manager:
    image: wazuh/wazuh-manager:4.7.0
    container_name: wazuh.manager
    hostname: wazuh.manager
    environment:
      - INDEXER_URL=http://wazuh.indexer:9200
      - INDEXER_USERNAME=""
      - INDEXER_PASSWORD=""
      - FILEBEAT_SSL_VERIFICATION_MODE=none
      # - FILEBEAT_ENABLED=false
      - SSL_CERTIFICATE_AUTHORITIES=""
      - SSL_CERTIFICATE=""
      - SSL_KEY=""
    volumes:
      - wazuh-manager-config:/wazuh-config-mount/etc/ossec
      - wazuh-manager-logs:/var/ossec/logs
      - wazuh-manager-queue:/var/ossec/queue
      - wazuh-manager-var-multigroups:/var/ossec/var/multigroups
      - wazuh-manager-integrations:/var/ossec/integrations
      - wazuh-manager-active-response:/var/ossec/active-response/bin
      - wazuh-manager-agentless:/var/ossec/agentless
      - wazuh-manager-wodles:/var/ossec/wodles
      - filebeat-etc:/etc/filebeat
      - filebeat-var:/var/lib/filebeat
      - C:\Users\Sriram.s\Documents\GitHub\SecurityMonitoringApp\SecurityMonitoringApp\config\filebeat\filebeat.yml:/etc/filebeat/filebeat.yml
    command: >
        bash -c "
          rm -rf /var/lib/filebeat/registry/.filebeat.lock 2>/dev/null || true &&
          until [ -f /etc/filebeat/filebeat.yml ]; do sleep 1; done &&
          until [ -d /var/lib/filebeat/registry ]; do sleep 1; done &&
          rm -f /var/lib/filebeat/registry/.filebeat.lock &&
          /init
        "
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "56000:55000"
    depends_on:
      wazuh.indexer:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f -k https://localhost:56000 || exit 1"]
      interval: 30s
      timeout: 60s
      retries: 30
      start_period: 120s
    networks:
      - wazuh

  # filebeat:
  #     image: docker.elastic.co/beats/filebeat:7.10.2
  #     container_name: filebeat
  #     user: root
  #     volumes:
  #       - ./config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
  #       - wazuh-manager-logs:/var/ossec/logs:ro
  #       - filebeat-data:/usr/share/filebeat/data
  #     depends_on:
  #       - wazuh.indexer
  #       - wazuh.manager
  #     networks:
  #       - wazuh

  # Wazuh dashboard
  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.7.0
    container_name: wazuh.dashboard
    hostname: wazuh.dashboard
    environment:
      - INDEXER_USERNAME=""
      - INDEXER_PASSWORD=""
      - WAZUH_API_URL=https://wazuh.manager
      - DASHBOARD_USERNAME=kibanaserver
      - DASHBOARD_PASSWORD=kibanaserver
      - API_USERNAME=wazuh-wui
      - API_PASSWORD=MyS3cr37P450r.*-
      - OPENSEARCH_HOSTS=http://wazuh.indexer:9200
      - SERVER_SSL_ENABLED=false
      - OPENSEARCH_SSL_VERIFICATIONMODE=none
    volumes:
      - wazuh-dashboard-config:/usr/share/wazuh-dashboard/data/wazuh/config
      - wazuh-dashboard-custom:/usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom
    ports:
      - "5601:5601"  # Changed from 443 to avoid SSL issues
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601 || exit 1"]
      interval: 30s
      timeout: 60s
      retries: 30
    depends_on:
      wazuh.manager:
        condition: service_healthy
      wazuh.indexer:
        condition: service_healthy
    networks:
      - wazuh

  # MongoDB for Graylog
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    networks:
      - wazuh
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 10s
      retries: 20

  # Elasticsearch for Graylog
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - network.host=0.0.0.0
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - wazuh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 20

  # Graylog
  graylog:
    image: graylog/graylog:5.1
    container_name: graylog
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
    depends_on:
      mongodb:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy 
    volumes:
      - graylog-data:/usr/share/graylog/data
    ports:
      - "9000:9000"
      - "12201:12201/udp"
    networks:
      - wazuh
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/api/system/lbstatus || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  # Your ASP.NET Core app
  security-monitoring-app:
    build: .
    container_name: security-monitoring-app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Wazuh__Host=http://wazuh.manager:56000
      - Wazuh__User=wazuh-wui
      - Wazuh__Password=MyS3cr37P450r.*-
      - Graylog__Host=graylog
      - Graylog__Port=12201
    ports:
      - "8070:80"
    depends_on:
      graylog:
        condition: service_healthy
      # wazuh.manager:
      #   condition: service_healthy
    restart: unless-stopped
    networks:
      - wazuh

volumes:
  wazuh-indexer-data:
  wazuh-manager-config:
  wazuh-manager-logs:
  wazuh-manager-queue:
  wazuh-manager-var-multigroups:
  wazuh-manager-integrations:
  wazuh-manager-active-response:
  wazuh-manager-agentless:
  wazuh-manager-wodles:
  wazuh-dashboard-config:
  wazuh-dashboard-custom:
  filebeat-etc:
  filebeat-var:
  mongodb-data:
  elasticsearch-data:
  graylog-data:
  # filebeat-data:

networks:
  wazuh:
    driver: bridge



