# Filebeat configuration for Wazuh
# Save this as: ./config/filebeat/filebeat.yml

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/ossec/logs/alerts/alerts.json
  fields:
    logtype: wazuh-alerts
  fields_under_root: true
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: log

- type: log
  enabled: true
  paths:
    - /var/ossec/logs/archives/archives.json
  fields:
    logtype: wazuh-archives
  fields_under_root: true
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: log

output.elasticsearch:
  hosts: ["http://wazuh.indexer:9200"]
  indices:
    - index: "wazuh-alerts-4.x-%{+yyyy.MM.dd}"
      when.equals:
        logtype: "wazuh-alerts"
    - index: "wazuh-archives-4.x-%{+yyyy.MM.dd}"
      when.equals:
        logtype: "wazuh-archives"

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
  index.number_of_replicas: 0

setup.ilm.enabled: false

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded