filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/ossec/logs/alerts/alerts.json
    json.keys_under_root: true
    json.overwrite_keys: true
    fields:
      logtype: wazuh-alerts
    fields_under_root: true

output.elasticsearch:
  hosts: ["http://wazuh.indexer:9200"]
  protocol: "http"
  index: "wazuh-alerts-%{+yyyy.MM.dd}"

setup.template.enabled: true
setup.template.name: "wazuh"
setup.template.pattern: "wazuh-alerts-*"
setup.template.overwrite: true
setup.template.settings:
  index:
    number_of_shards: 1
    number_of_replicas: 0
    codec: best_compression
    refresh_interval: 5s

setup.ilm.enabled: false

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_fields:
      target: ''
      fields:
        event.module: wazuh

# Use the mounted volume path
path.data: /var/lib/filebeat
path.logs: /var/log/filebeat